In [1]:
# import required modules
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
pd.pandas.set_option("display.max_columns", None)

In [2]:
# dataframe for EV dataset
df = pd.read_csv("Electric_Vehicle_Population_Data.csv")

In [3]:
df.head()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,5YJSA1E65N,Yakima,Granger,WA,98932.0,2022,TESLA,MODEL S,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,0.0,15.0,187279214,POINT (-120.1871 46.33949),PACIFICORP,5.307700e+10
1,KNDC3DLC5N,Yakima,Yakima,WA,98902.0,2022,KIA,EV6,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,0.0,15.0,210098241,POINT (-120.52041 46.59751),PACIFICORP,5.307700e+10
2,5YJYGDEEXL,Snohomish,Everett,WA,98208.0,2020,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,291.0,0.0,44.0,121781950,POINT (-122.18637 47.89251),PUGET SOUND ENERGY INC,5.306104e+10
3,3C3CFFGE1G,Yakima,Yakima,WA,98908.0,2016,FIAT,500,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,84.0,0.0,14.0,180778377,POINT (-120.60199 46.59817),PACIFICORP,5.307700e+10
4,KNDCC3LD5K,Kitsap,Bremerton,WA,98312.0,2019,KIA,NIRO,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,26.0,0.0,26.0,2581225,POINT (-122.65223 47.57192),PUGET SOUND ENERGY INC,5.303508e+10

In [4]:
# check the dimensionality of the dataset

df.shape

(250659, 17)

Data Cleaning
  .Check for missing or null values
  .Check for rows with duplicate values
  .Drop non-required rows
  . Check data type
  .Understand dataset

In [5]:
null_features = [features for features in df.columns if df[features].isnull().sum()>=1]
for f in null_features:
    print(f, np.round(df[f].isnull().mean()*100,5), '% missing values')

County 0.00239 % missing values
City 0.00239 % missing values
Postal Code 0.00239 % missing values
Electric Range 0.00838 % missing values
Base MSRP 0.00838 % missing values
Legislative District 0.23259 % missing values
Vehicle Location 0.00559 % missing values
Electric Utility 0.00239 % missing values
2020 Census Tract 0.00239 % missing values

In [6]:
null_features

['County',
 'City',
 'Postal Code',
 'Electric Range',
 'Base MSRP',
 'Legislative District',
 'Vehicle Location',
 'Electric Utility',
 '2020 Census Tract']

In [7]:
# check the null values in the columns
number_of_null = df.isnull().sum()
print("The null values", number_of_null)

The null values VIN (1-10)                                             0
County                                                 6
City                                                   6
State                                                  0
Postal Code                                            6
Model Year                                             0
Make                                                   0
Model                                                  0
Electric Vehicle Type                                  0
Clean Alternative Fuel Vehicle (CAFV) Eligibility      0
Electric Range                                        21
Base MSRP                                             21
Legislative District                                 583
DOL Vehicle ID                                         0
Vehicle Location                                      14
Electric Utility                                       6
2020 Census Tract                                      6
dtype: int64

In [8]:
df.dropna(inplace=True)

In [9]:
df.shape

(250047, 17)

In [10]:
# check for rows with duplicate values

duplicate_rows = df.duplicated().sum()
print("Duplicated rows", duplicate_rows)

Duplicated rows 0

In [11]:
# drop non-required columns
columns_to_remove = ['VIN (1-10)', 'DOL Vehicle ID', 'Vehicle Location', '2020 Census Tract', 'State', 'County', 'City', 'Postal Code' ]
for f in columns_to_remove:
    df.drop(f, inplace=True, axis=1)

In [12]:
# check the new dataframe 
df.head()

,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,Electric Utility
0,2022,TESLA,MODEL S,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,0.0,15.0,PACIFICORP
1,2022,KIA,EV6,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,0.0,15.0,PACIFICORP
2,2020,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,291.0,0.0,44.0,PUGET SOUND ENERGY INC
3,2016,FIAT,500,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,84.0,0.0,14.0,PACIFICORP
4,2019,KIA,NIRO,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,26.0,0.0,26.0,PUGET SOUND ENERGY INC